/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kaniaveha.aliaksei.citadel;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class AppTest {

  @Test
  void contextLoads() {
    // no explicit assertions - test fails if context cannot be loaded, otherwise it's just green
  }
}
