/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kaniaveha.aliaksei.exray;

import org.junit.jupiter.api.Test;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.equalTo;

class AppTest {

  App testee = new App();

  @Test
  void appHasAGreeting() {
    assertThat(testee.getGreeting(), equalTo("Hello!1"));
  }
}
