name: Release to Production

on:
  workflow_dispatch:

jobs:
  system-tests:
    name: Release to Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build App
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.2
          arguments: build -x test --info
      - name: Build Image and Push
        run: |
          docker login -u epamaliakseikaniaveha -p '${{ secrets.DOCKERPASSWORD }}'
          docker build -f containers/citadel-app.dockerfile -t epamaliakseikaniaveha/citadel-app:0.0.1 .
          docker push epamaliakseikaniaveha/citadel-app:0.0.1
