name: Release to Production

on:
  workflow_dispatch:

jobs:
  system-tests:
    name: Release to Production
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        run: |
          docker login -u epamaliakseikaniaveha -p '${{ secrets.DOCKERPASSWORD }}'
      - name: Check if not released yet
        run: |
          docker manifest inspect epamaliakseikaniaveha/citadel-app:0.0.5 &> manifest.out || true
          manifestResult=$(cat manifest.out)
          if [[ "$manifestResult" == *"no such manifest"* ]];
          then
            echo '0.0.5 not released yet, good to go';
          else
            echo '0.0.5 version already released, check https://hub.docker.com/repository/docker/epamaliakseikaniaveha/citadel-app'
            echo 'To raise version update https://github.com/AliakseiKaniaveha/citadel/blob/master/src/main/resources/version'
            exit 1;
          fi
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build App
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.2
          arguments: build -x test --info
      - name: Build Image and Push
        run: |
          docker build -f containers/citadel-app.dockerfile -t epamaliakseikaniaveha/citadel-app:0.0.5 -t epamaliakseikaniaveha/citadel-app:latest .
          docker push epamaliakseikaniaveha/citadel-app:0.0.5
          docker push epamaliakseikaniaveha/citadel-app:latest
